export enum BotState {
  INICIO                  = 'INICIO',
  ESPERANDO_CONFIRMACION  = 'ESPERANDO_CONFIRMACION',
  IDENTIFICACION          = 'IDENTIFICACION',
  DATOS_NUEVO_CLIENTE     = 'DATOS_NUEVO_CLIENTE',
  SELECCION_PRODUCTOS     = 'SELECCION_PRODUCTOS',
  CONFIRMACION_PRODUCTOS  = 'CONFIRMACION_PRODUCTOS',
  DATOS_ENVIO             = 'DATOS_ENVIO',
  FINALIZADO              = 'FINALIZADO',
  CANCELADO               = 'CANCELADO',
}
